name: boring_table
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.5
  linked_scroll_controller: ^0.2.0
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null

